#pragma once

struct WeatherPresetData {
    bool forceClearSky = false;
    float rain = 0.0f;
    float dust = 0.0f;
    float snow = 0.0f;
    bool visualTimeOverride = false;
    float timeHour = 12.0f;
    bool cloudAmountEnabled = false;
    float cloudAmount = 1.0f;
    bool cloudHeightEnabled = false;
    float cloudHeight = 1.0f;
    bool cloudDensityEnabled = false;
    float cloudDensity = 1.0f;
    bool midCloudsEnabled = false;
    float midClouds = 1.0f;
    bool highCloudsEnabled = false;
    float highClouds = 1.0f;
    bool exp2CEnabled = false;
    float exp2C = 1.0f;
    bool exp2DEnabled = false;
    float exp2D = 1.0f;
    bool cloudVariationEnabled = false;
    float cloudVariation = 1.0f;
    bool nightSkyRotationEnabled = false;
    float nightSkyRotation = 0.0f;
    bool nightSkyYawEnabled = false;
    float nightSkyYaw = 0.0f;
    bool sunSizeEnabled = false;
    float sunSize = 0.267f;
    bool sunYawEnabled = false;
    float sunYaw = 0.0f;
    bool sunPitchEnabled = false;
    float sunPitch = 0.0f;
    bool moonSizeEnabled = false;
    float moonSize = 0.267f;
    bool moonYawEnabled = false;
    float moonYaw = 0.0f;
    bool moonPitchEnabled = false;
    float moonPitch = 0.0f;
    bool moonRollEnabled = false;
    float moonRoll = 0.0f;
    bool fogEnabled = false;
    float fogPercent = 0.0f;
    bool nativeFogEnabled = false;
    float nativeFog = 0.0f;
    bool noFog = false;
    float wind = 1.0f;
    bool noWind = false;
    bool puddleScaleEnabled = false;
    float puddleScale = 0.0f;
};

constexpr int kPresetRegionGlobal = 0;
constexpr int kPresetRegionHernand = 1;
constexpr int kPresetRegionDemeniss = 2;
constexpr int kPresetRegionDelesyia = 3;
constexpr int kPresetRegionPailune = 4;
constexpr int kPresetRegionCrimsonDesert = 5;
constexpr int kPresetRegionAbyss = 6;
constexpr int kPresetRegionCount = 7;

struct WeatherPresetSourceMask {
    bool forceClearSky = false;
    bool rain = false;
    bool dust = false;
    bool snow = false;
    bool time = false;
    bool cloudAmount = false;
    bool cloudHeight = false;
    bool cloudDensity = false;
    bool midClouds = false;
    bool highClouds = false;
    bool exp2C = false;
    bool exp2D = false;
    bool cloudVariation = false;
    bool nightSkyRotation = false;
    bool nightSkyYaw = false;
    bool sunSize = false;
    bool sunYaw = false;
    bool sunPitch = false;
    bool moonSize = false;
    bool moonYaw = false;
    bool moonPitch = false;
    bool moonRoll = false;
    bool fog = false;
    bool nativeFog = false;
    bool noFog = false;
    bool wind = false;
    bool noWind = false;
    bool puddleScale = false;
};

struct WeatherPresetStatusSnapshot {
    bool hasPresetPackage = false;
    int playerRegion = kPresetRegionGlobal;
    int editRegion = kPresetRegionGlobal;
    int blendFromRegion = -1;
    int blendToRegion = -1;
    float blendProgress = 1.0f;
    WeatherPresetData effective{};
    WeatherPresetSourceMask regionSource{};
};

void Preset_EnsureInitialized();
void Preset_Refresh();
int Preset_GetCount();
const char* Preset_GetDisplayName(int index);
int Preset_GetSelectedIndex();
bool Preset_HasSelection();
const char* Preset_GetSelectedDisplayName();
const char* Preset_GetRegionDisplayName(int regionId);
int Preset_GetEditRegion();
void Preset_SetEditRegion(int regionId);
bool Preset_SelectedHasRegion(int regionId);
bool Preset_IsEditingDetachedRegion();
WeatherPresetData Preset_GetEditRegionData();
WeatherPresetSourceMask Preset_GetEditRegionOverrideMask();
void Preset_SetEditRegionData(const WeatherPresetData& data);
void Preset_SetEditRegionDataWithOverrides(const WeatherPresetData& data, const WeatherPresetSourceMask& mask);
void Preset_ResetEditRegion();
void Preset_SelectNew();
bool Preset_SelectIndex(int index);
bool Preset_HasUnsavedChanges();
bool Preset_CanSaveCurrent();
WeatherPresetStatusSnapshot Preset_GetStatusSnapshot();
void Preset_ArmAutoApplyRemembered();
void Preset_OnWorldTick(bool worldReady, float dt);
void Preset_TryAutoApplyRemembered();
bool Preset_SaveSelected();
bool Preset_SaveAs(const char* fileName);
